### ISSUE TITLE
Cannot create integration in HA 2022.6.7

### ISSUE THREAD

**Issue by turbatus** [puttyman/hass-amplifi#21] opened 2022-06-23 08:24 UTC
I installed the repo through HACS, but I could not find the integration in Config -> Integrations -> Add
The component is in custom_components folder, restarted HA many times, cleared browser cache, no joy.
Is it compatible with HA 2022.6.7?
Thank you.

**Comment by wbste** [comment] 2022-07-31 00:35
Same issue as above. Happy to troubleshoot if needed.
On 2022.7.7 HA Core and 8.2 HA OS.
After a few reboots (to make sure I didn't miss anything) went to Settings > Devices & Services > Add Integration > and `Amplifi` doesn't show.

Confirmed on HACS I have 2.0.0 installed, and saw it in SMB it was installed \\server\config\custom_components\amplifi\
**DO NOTE** I didn't see entries for the plugin in configuration.yaml...not sure if I was supposed to do anything there since I used HACS to install.

**Comment by wbste** [comment] 2022-07-31 00:53
FYI Just upgraded to HA OS 8.4 and it pops up now!

**Comment by CWoldendorp** [comment] 2022-09-19 06:29
Also having the same problem. Running on latest versions:
HA 2022.9.5
OS 9.0

Happy to troubleshoot!

**Comment by LesVrbe** [comment] 2022-10-16 19:40
Same Issue here also.
Just tried to install on clean HA setup.

HA 2022.10.4
OS 9.2

**Comment by LesVrbe** [comment] 2022-10-17 18:38
> Same Issue here also. Just tried to install on clean HA setup.
> 
> HA 2022.10.4 OS 9.2

I've got it working now,
Added the Integration trough HACS itself.

So

HACS > Integrations > Explore & Download repositories > Search Amplifi

then you'll need to download & Restart Home assistant

Afterwards you'll find the Amplifi integration in the devices tab.

**Comment by hawksj** [comment] 2024-04-29 13:36
This integration should be working with the latest version of home assistant. Due to the age of this issue, I will close it but please recreate if issues persist in new versions.

**Closed as completed by hawksj** 2024-04-29 13:36 UTC
