### ISSUE TITLE
Version 2.0.0 - Error Loading Integration

### ISSUE THREAD

**Issue by townsmcp** [puttyman/hass-amplifi#10] opened 2021-09-11 08:49 UTC
Getting the following error message in the logs after updating to 2.0.0:
![image](https://user-images.githubusercontent.com/14061617/132942088-cfe3db41-7f87-44d1-bc8e-afea3d27458c.png)

To try and resolve the issue I have:

- Removed the integration from Configuration - Integrations
- Removed the custom component from HACS
- Rebooted HA
- Go back into HACS and install custom integration
- Rebooted HA
- Load a Chrome Incognito window
- Go back into Configuration - Integrations
- Add Amplifi integration
- Enter IP address and password (no error message observed)
- Observed on Configuration - Integrations page the following:
![image](https://user-images.githubusercontent.com/14061617/132942193-c897d0d4-f6b3-4a0b-892d-d7f7c085ecf2.png)

My HA is containered, and running the following version:
![image](https://user-images.githubusercontent.com/14061617/132942224-84a674a5-95ce-4300-987b-d4f6a99e869f.png)

HACS is running the following version:
![image](https://user-images.githubusercontent.com/14061617/132942238-06a4eb84-35a7-45d5-94c8-5a5efd881e51.png)

Also enabled logging and getting this error in the logs:
![image](https://user-images.githubusercontent.com/14061617/132943010-05753531-bd61-4f2f-899f-2f1d37d9a90f.png)

**Comment by puttyman** [comment] 2021-09-11 09:29
Can you provide a screenshot of below:

1. Login to http://amplifi.lan/info.php
2. On Chrome open your developer console
3. Click on the network tab
4. Click on info-async.php
5. Click on preview tab and expand

Example below:
![image](https://user-images.githubusercontent.com/980155/132943186-cff139f9-22d3-4883-8386-f9af575b7d3e.png)

Also how is your router setup? e.g. How many mesh points and additional router you have setup in mesh?

**Comment by townsmcp** [comment] 2021-09-11 09:46
I have 2 Aliens, both are main Alien units, one is working as a slave for repeating wifi. The slave is hardwired rather than wireless meshing.
The Aliens are working in Bridge mode.
Also, im running firmware 3.6.1rc4
![image](https://user-images.githubusercontent.com/14061617/132943816-f1a87c3e-84e5-44bc-bfd1-6be16bfb47be.png)

**Comment by puttyman** [comment] 2021-09-11 10:21
@townsmcp unfortunately this integration is for Amplifi HD only - https://store.amplifi.com/products/amplifi-hd-mesh-router . But since you were able to get pass the login it seems the integration can be extended to work for Alien. I do not have one unfortunately. 

If you are a developer feel free to submit a PR. The issue is related to the structure of response of Alien is different from HD. Looks like Alien returns more info.

**Comment by townsmcp** [comment] 2021-09-11 10:43
@puttyman unfortunately I’m not a dev ☹️
The previous version worked well with Alien. I switched over to the pull request here https://github.com/hanswilw/hass-amplifi to use device_tracker rather than sensor (this one is still working) but would have rather gone back to source via your code. Will see if I can do some sort of comparison between your code and the other version - hehe you never know, it might be possible to get Aliens working again 😉

**Comment by jpsmith16** [comment] 2021-09-11 19:46
I seem to be having a similar issue. I've an Amplifi HD system is set up with 1 router and 4x routers as mesh points (RAMPS). Set up in Bridged Mode and all 4 RAMPs are connected via ethernet backbone. Running firmware 3.6.1 on all. I've included screenshots below. Sorry if the info-async.php one  is not what's needed. Previously used same set up with the integration without issue, up until the HA version key requirement

![Screenshot 2021-09-11 at 20 43 31](https://user-images.githubusercontent.com/52608556/132959694-efe261ca-0394-4754-96ee-a87fe4f79c08.png)


![Screenshot 2021-09-11 at 20 07 58](https://user-images.githubusercontent.com/52608556/132959073-1c973b4e-4c35-47c2-bf4d-33eb1e06b5e0.png)
![Screenshot 2021-09-11 at 20 38 19](https://user-images.githubusercontent.com/52608556/132959587-9215fe0d-e66e-43ad-b09a-671cb3dbe763.png)

![Screenshot 2021-09-11 at 20 06 57](https://user-images.githubusercontent.com/52608556/132959084-e78f22ce-ce0e-4fe1-91db-41de3d965cdd.png)

![Screenshot 2021-09-11 at 20 40 28](https://user-images.githubusercontent.com/52608556/132959634-3b40af29-7585-41a7-a44f-229b92f0534e.png)

![Screenshot 2021-09-11 at 20 39 56](https://user-images.githubusercontent.com/52608556/132959638-b11a93b8-b9d9-46a0-a1dc-89a0421ce234.png)


![Screenshot 2021-09-11 at 20 39 28](https://user-images.githubusercontent.com/52608556/132959603-3befb6df-d9e0-46b7-8f96-42727d7ebd9d.png)


![Screenshot 2021-09-11 at 20 29 18](https://user-images.githubusercontent.com/52608556/132959452-5b2cac91-dfd4-4ff7-8341-d0c13925b7c1.png)

**Comment by puttyman** [comment] 2021-09-12 04:34
@jpsmith16 @townsmcp can you please attach the whole content of the info-async.php. Feel free to modify any content for your security. Before you attach them check if it is valid json https://jsonlint.com/ after altering the content.

I'll take it a look and have it work for both.

**Comment by townsmcp** [comment] 2021-09-12 06:23
Sure. Find attached for the Alien file
[info-async.log](https://github.com/puttyman/hass-amplifi/files/7149108/info-async.log)

**Comment by puttyman** [comment] 2021-09-12 08:49
Pushed a fix for that. Let me know how you go.

**Comment by townsmcp** [comment] 2021-09-12 11:52
@puttyman i have installed the update and all is working perfectly on Aliens - all devices are showing and when a device disconnects and reconnects that is updated in status. 

One suggested future change if at all possible might be delay the device_tracker showing as away immediately - delay the away status change to 3 or 5 minutes before the device is marked away? Or ideally to make it a configurable period so the user can choose how long a device is off Wi-fi before status changes to away (I believe iPhones still go into deep sleep and drop Wi-fi connection even though at home)

**Comment by jpsmith16** [comment] 2021-09-12 13:39
@puttyman Attached is my info-async file. Did put it through jsonlint.com, so hopefully it's what you need

I did update the Integration based on the one you released earlier today and still getting error


![Screenshot 2021-09-12 at 14 35 15](https://user-images.githubusercontent.com/52608556/132989707-14dfdbea-47fd-4716-ba8f-3f438b429fa6.png)

![Screenshot 2021-09-12 at 14 36 42](https://user-images.githubusercontent.com/52608556/132989794-e27e8f7c-eb43-4acb-a1ab-a010b8ee2b77.png)

**Comment by arboeh** [comment] 2021-09-12 16:04
Same issue for me. Everything updated to latest versions. Still getting the error described above.

**Comment by lohita** [comment] 2021-09-16 10:38
Same issue for me even after the latest updates.

**Comment by Gorbac** [comment] 2021-09-16 17:01
I've the same problem

**Comment by teaching-innovation** [comment] 2021-09-17 22:41
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/amplifi/coordinator.py:79 
Integration: Amplifi (documentation, issues) 
First occurred: 7:48:20 (88 occurrences) 
Last logged: 8:02:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/amplifi/coordinator.py", line 79, in extract_ethernet_ports
    self._ethernet_ports = self.data[ETHERNET_PORTS_IDX][router_mac_addr]
KeyError: None

**Comment by puttyman** [comment] 2021-09-18 00:12
All those having issues can you please post the info-async.php as mentioned above. Also please do not replace the whole mac addresses instead you may find and replace the mac you'd like to hide. 

E.g. if the mac is 66:22:22:11:77 replace all 66:22:22:11:77 with an actual valid dummy mac.

**Comment by arboeh** [comment] 2021-09-18 08:11
Are you serious to post the whole info-async.php response?
That response is full of MAC- and IP-addresses...
I would send it to you via e-mail.

**Comment by jpsmith16** [comment] 2021-09-18 12:47
> All those having issues can you please post the info-async.php as mentioned above. Also please do not replace the whole mac addresses instead you may find and replace the mac you'd like to hide.
> 
> E.g. if the mac is 66:22:22:11:77 replace all 66:22:22:11:77 with an actual valid dummy mac.

Have updated my file based on this. Hopefully this works for you to enable a fix soon?

**Comment by selhammer** [comment] 2021-09-19 19:04
Hi
Just installed hass-amplifi and experience the same as above, Failed to setup. Guess I have the latest since I installed it some hour ago :)

Im using Amplify Mech HD with two mesh points and no other router.

What part of info.php are you interested in?

**Comment by arboeh** [comment] 2021-09-20 05:47
My response file. Was "a little bit" of work to change every security relevant info :-|
Hope it helps to fix the issue.
[info-async.json.txt](https://github.com/puttyman/hass-amplifi/files/7193753/info-async.json.txt)

**Comment by puttyman** [comment] 2021-09-21 00:42
@arboeh Are you having same issue as https://github.com/puttyman/hass-amplifi/issues/10#issuecomment-922118659 ? If not please post your logs.

**Comment by arboeh** [comment] 2021-09-21 05:58
Hey @puttyman. Log is:

2021-09-21 07:55:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.0.218 for amplifi
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/amplifi/__init__.py", line 32, in async_setup_entry
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 156, in async_config_entry_first_refresh
await self._async_refresh(log_failures=False, raise_on_auth_failed=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/config/custom_components/amplifi/coordinator.py", line 79, in extract_ethernet_ports
self._ethernet_ports = self.data[ETHERNET_PORTS_IDX][router_mac_addr]
KeyError: None
2021-09-21 07:56:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/config/custom_components/amplifi/coordinator.py", line 79, in extract_ethernet_ports
self._ethernet_ports = self.data[ETHERNET_PORTS_IDX][router_mac_addr]
KeyError: None

**Comment by Horsboell** [comment] 2021-09-22 17:18
On the road atm so no logs, but just chiming in to sat that I have the same issue after upgrading. Hopefully some of the above will solve my issue as well - great work on the integration - many thanks  :)

**Comment by puttyman** [comment] 2021-09-25 06:05
@arboeh pushed a fix based on the data from your router response. Hopefully that should fix it for everyone. If not then reopen this issue.

**Closed as completed by puttyman** 2021-09-25 06:05 UTC

**Comment by C0NTi** [comment] 2021-09-25 06:30
> @arboeh pushed a fix based on the data from your router response. Hopefully that should fix it for everyone. If not then reopen this issue.

Updated to this latest version and I no longer get the error.  many thanks @puttyman your integration has basically replaced all my presence detection measures!

**Comment by arboeh** [comment] 2021-09-25 07:46
@puttyman Thanks, works again. Great integration. If you need any help again, feel free to ask.

**Comment by teaching-innovation** [comment] 2021-09-25 09:08
Legend. Thank you. Now HA can tell me when my in law’s arrive again.

**Comment by Horsboell** [comment] 2021-09-26 07:06
Working here again as well. Thanks a bunch for the effort @puttyman - this is the backbone of my presence-detection. You're a legend.

**Comment by jpsmith16** [comment] 2021-09-26 09:32
Back working here too. Many thanks for your help!

**Comment by lohita** [comment] 2021-09-26 11:24
And here too! Thanks Puttyman!

Regards,

Lohita
